import carImage1 from "../assets/image1.jpg";
import carImage2 from "../assets/image2.jpg";
import carImage3 from "../assets/image3.jpg";
import carImage4 from "../assets/image4.jpg";
import carImage5 from "../assets/image5.jpg";
import carImage6 from "../assets/image6.jpg";
import carImage7 from "../assets/image7.jpg";
import carImage8 from "../assets/image8.jpg";
import carImage9 from "../assets/image9.jpg";
import carImage10 from "../assets/image10.jpg";
import carImage11 from "../assets/image11.jpg";
import carImage12 from "../assets/image12.jpg";
import carImage13 from "../assets/image13.jpg";
import carImage14 from "../assets/image14.jpg";
import carImage15 from "../assets/image15.jpg";
import carImage16 from "../assets/image16.jpg";
import carImage17 from "../assets/image17.jpg";
import carImage18 from "../assets/image18.jpg";
import carImage19 from "../assets/image19.jpg";
import carImage20 from "../assets/image20.jpg";

export const carsData = [
  {
    id: 1,
    image: carImage1,
    make: "Hyundai",
    model: "Creta",
    price: 19500,
    mileage: 51000,
    gearbox: "Automatic",
    firstRegistration: "09/2022",
    fuelType: "Gasoline",
  },
  {
    id: 2,
    image: carImage2,
    make: "Toyota",
    model: "Rumion",
    price: 25000,
    mileage: 85000,
    gearbox: "Manual",
    firstRegistration: "04/2021",
    fuelType: "Gasoline",
  },
  {
    id: 3,
    image: carImage3,
    make: "Honda",
    model: "Elevata",
    price: 30000,
    mileage: 85000,
    gearbox: "Automatic",
    firstRegistration: "03/2023",
    fuelType: "Electric",
  },
  {
    id: 4,
    image: carImage4,
    make: "Volkswagen ",
    model: "Virtus",
    price: 22000,
    mileage: 11100,
    gearbox: "Automatic",
    firstRegistration: "10/2022",
    fuelType: "Gasoline",
  },
  {
    id: 5,
    image: carImage5,
    make: "Mercedes-Benz ",
    model: "EQE SUV",
    price: 60000,
    mileage: 10000,
    gearbox: "Automatic",
    firstRegistration: "11/2023",
    fuelType: "Gasoline",
  },
  {
    id: 6,
    image: carImage6,
    make: "Lamborghini Urus ",
    model: "Performante",
    price: 120000,
    mileage: 23000,
    gearbox: "Automatic",
    firstRegistration: "03/2023",
    fuelType: "Gasoline",
  },
  {
    id: 7,
    image: carImage7,
    make: "Mercedes-Benz ",
    model: "GLC",
    price: 55000,
    mileage: 0,
    gearbox: "Automatic",
    firstRegistration: "07/2023",
    fuelType: "Gasoline",
  },
  {
    id: 8,
    image: carImage8,
    make: "Volvo C40 ",
    model: "Recharge",
    price: 70000,
    mileage: 0,
    gearbox: "Automatic",
    firstRegistration: "03/2022",
    fuelType: "Gasoline",
  },
  {
    id: 9,
    image: carImage9,
    make: "Volkswagen ",
    model: "Taigun",
    price: 80000,
    mileage: 35000,
    gearbox: "Manual",
    firstRegistration: "01/2022",
    fuelType: "Gasoline",
  },
  {
    id: 10,
    image: carImage10,
    make: "Jeep",
    model: "Grand Cherokee",
    price: 65000,
    mileage: 15000,
    gearbox: "Automatic",
    firstRegistration: "02/2023",
    fuelType: "Gasoline",
  },
  {
    id: 11,
    image: carImage11,
    make: "Skoda ",
    model: "Kushaq",
    price: 25000,
    mileage: 90000,
    gearbox: "Automatic",
    firstRegistration: "03/2023",
    fuelType: "Gasoline",
  },
  {
    id: 12,
    image: carImage12,
    make: "Nissan ",
    model: "Magnite",
    price: 72000,
    mileage: 50000,
    gearbox: "Automatic",
    firstRegistration: "07/2023",
    fuelType: "Gasoline",
  },
  {
    id: 13,
    image: carImage13,
    make: "Skoda ",
    model: "Slavia",
    price: 34000,
    mileage: 10000,
    gearbox: "Automatic",
    firstRegistration: "01/2022",
    fuelType: "Gasoline",
  },
  {
    id: 14,
    image: carImage14,
    make: "Land Rover ",
    model: "Range Rover",
    price: 65000,
    mileage: 17000,
    gearbox: "Automatic",
    firstRegistration: "06/2023",
    fuelType: "Gasoline",
  },
  {
    id: 15,
    image: carImage15,
    make: "Audi ",
    model: "Q3",
    price: 24000,
    mileage: 78000,
    gearbox: "Automatic",
    firstRegistration: "09/2020",
    fuelType: "Gasoline",
  },
  {
    id: 16,
    image: carImage16,
    make: "Hyundai ",
    model: "Exter",
    price: 37000,
    mileage: 43000,
    gearbox: "Automatic",
    firstRegistration: "05/2022",
    fuelType: "Gasoline",
  },
  {
    id: 17,
    image: carImage17,
    make: "Lexus ",
    model: "Es",
    price: 31000,
    mileage: 122000,
    gearbox: "Automatic",
    firstRegistration: "08/2018",
    fuelType: "Gasoline",
  },
  {
    id: 18,
    image: carImage18,
    make: "Bentley ",
    model: "Bentayga",
    price: 187000,
    mileage: 12000,
    gearbox: "Automatic",
    firstRegistration: "08/2022",
    fuelType: "Gasoline",
  },
  {
    id: 19,
    image: carImage19,
    make: "Isuzu ",
    model: "MU-X",
    price: 87000,
    mileage: 98000,
    gearbox: "Automatic",
    firstRegistration: "04/2022",
    fuelType: "Gasoline",
  },
  {
    id: 20,
    image: carImage20,
    make: "Kia ",
    model: "EV6",
    price: 62000,
    mileage: 98000,
    gearbox: "Automatic",
    firstRegistration: "08/2022",
    fuelType: "Gasoline",
  },
];

export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it works", url: "/" },
      { title: "Featured", url: "/" },
      { title: "Partnership", url: "/" },
      { title: "Bussiness Relation", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Events", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Podcast", url: "/" },
      { title: "Invite a friend", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Discord", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];
